# https://golangci-lint.run/usage/configuration/
version: "2"

linters:
  default: none
  enable:
    # Correctness
    - errcheck        # unchecked errors
    - govet           # go vet checks (includes printf, shadow, etc.)
    - staticcheck     # staticcheck SA rules
    - ineffassign     # ineffectual assignments
    - unused          # unused code

    # Code quality
    - misspell        # typos in comments/strings
    - unconvert       # unnecessary type conversions
    - unparam         # unused function parameters

    # Security
    - gosec           # common security issues

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment  # not worth optimizing struct layout manually
        - shadow          # too noisy; := in if/loop blocks is idiomatic Go

    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close

    gosec:
      excludes:
        - G103  # unsafe calls — required for Windows registry/syscall APIs
        - G115  # int->uint32 — safe for fixed-size registry buffer lengths
        - G204  # subprocess with variable — intentional (self-elevation)
        - G302  # file perms 0644 — acceptable for append-only log file
        - G304  # file via variable — intentional (--config flag)

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/kad/WindowsBrowserGuard

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
