# GoReleaser configuration for Windows Browser Guard
# https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    - go mod download

builds:
  - id: WindowsBrowserGuard
    main: ./cmd/WindowsBrowserGuard
    binary: WindowsBrowserGuard

    # Windows only - uses Windows-specific registry APIs
    goos:
      - windows

    goarch:
      - amd64

    env:
      - CGO_ENABLED=0

    flags:
      - -trimpath

    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    files:
      - README.md
      - Install.ps1
      - config.example.json
      - docs/start.ps1
      - docs/stop.ps1
      - docs/restart.ps1
      - docs/status.ps1
      - docs/view-logs.ps1
      - LICENSE*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Security Updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Documentation Updates'
      regexp: '^.*?doc(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: 'Other Changes'
      order: 999

release:
  draft: false
  prerelease: auto
  mode: replace

  header: |
    ## Windows Browser Guard {{ .Version }}

    Windows registry monitoring daemon that automatically detects and blocks forced
    browser extension installations via Group Policy.

    ### Features
    - Real-time registry monitoring under `HKLM\SOFTWARE\Policies`
    - Chrome extension protection (ExtensionInstallForcelist → ExtensionInstallBlocklist)
    - Firefox extension protection (ExtensionSettings with blocked installation_mode)
    - Reads configuration from `config.json` next to the executable (or `--config` flag)
    - OpenTelemetry traces, logs and metrics via OTLP (gRPC or HTTP)
    - Self-elevating installer with Task Scheduler integration (runs as SYSTEM at startup)

    ### Quick Start
    1. Download the ZIP and extract all files to a folder
    2. Right-click `Install.ps1` → "Run with PowerShell" (or run as Administrator)
    3. Follow the prompts — the installer configures OTLP endpoint and registers the startup task

    See README.md for detailed documentation.

  footer: |
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY }}/compare/{{ .PreviousTag }}...{{ .Tag }}

    ---

    ### Installation Notes
    - Windows only (amd64)
    - Administrator privileges required
    - Task Scheduler runs `WindowsBrowserGuard.exe --config="<install-path>\config.json"` as SYSTEM

    ### Verification
    ```powershell
    # Verify checksum (PowerShell)
    Get-FileHash WindowsBrowserGuard.exe -Algorithm SHA256
    ```

  name_template: "v{{ .Version }}"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

# Code signing (optional - configure if you have a code signing certificate)
# signs:
#   - cmd: signtool
#     args:
#       - "sign"
#       - "/f"
#       - "${CERTIFICATE_PATH}"
#       - "/p"
#       - "${CERTIFICATE_PASSWORD}"
#       - "/tr"
#       - "http://timestamp.digicert.com"
#       - "/td"
#       - "SHA256"
#       - "${artifact}"
#     artifacts: all
