# GoReleaser configuration for Registry Extension Monitor
# https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    - go mod download

builds:
  - id: printwatch
    main: ./printwatch.go
    binary: printwatch
    
    # Windows only - uses Windows-specific registry APIs
    goos:
      - windows
    
    goarch:
      - amd64
      - arm64
    
    env:
      - CGO_ENABLED=0
    
    flags:
      - -trimpath
    
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    
    # Build tags if needed
    # tags:
    #   - netgo

archives:
  - id: default
    format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    
    files:
      - README.md
      - install-task.ps1
      - uninstall-task.ps1
      - start-monitor.ps1
      - view-logs.ps1
      - LICENSE*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Security Updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Documentation Updates'
      regexp: '^.*?doc(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .ProjectName }}"
  
  draft: false
  prerelease: auto
  mode: replace
  
  header: |
    ## Registry Extension Monitor {{ .Version }}
    
    Windows registry monitoring tool that automatically detects and blocks browser extension installations.
    
    ### Features
    - Real-time registry monitoring under `HKLM\SOFTWARE\Policies`
    - Chrome extension protection (ExtensionInstallForcelist → ExtensionInstallBlocklist)
    - Firefox extension protection (ExtensionSettings with blocked installation_mode)
    - Detailed change tracking and diff display
    - Automatic privilege elevation
    
    ### Quick Start
    1. Download the appropriate ZIP file for your architecture
    2. Extract all files to a folder
    3. Right-click `install-task.ps1` → "Run with PowerShell" (as Administrator)
    4. Follow the prompts to install as a startup task
    
    See README.md for detailed documentation.
  
  footer: |
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ---
    
    ### Installation Notes
    - Requires Windows OS
    - Administrator privileges required for registry deletion
    - Run `install-task.ps1` to set up automatic startup
    
    ### Verification
    ```powershell
    # Verify checksum (PowerShell)
    Get-FileHash printwatch.exe -Algorithm SHA256
    ```
  
  name_template: "v{{ .Version }}"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

# Windows-specific metadata
nfpms:
  - id: default
    # Not applicable for Windows, but keeping structure for future Linux support
    builds:
      - printwatch
    formats: []

# Code signing (optional - configure if you have a code signing certificate)
# signs:
#   - cmd: signtool
#     args:
#       - "sign"
#       - "/f"
#       - "${CERTIFICATE_PATH}"
#       - "/p"
#       - "${CERTIFICATE_PASSWORD}"
#       - "/tr"
#       - "http://timestamp.digicert.com"
#       - "/td"
#       - "SHA256"
#       - "${artifact}"
#     artifacts: all

# Announcements (optional)
# announce:
#   discord:
#     enabled: true
#     message_template: 'New release {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}'
